### ISSUE TITLE
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.

### ISSUE THREAD

**Issue by lamboid** [GlobalPlusPlus/RocketMapPlusPlus#100]
## Expected Behavior
installation runs through with no error

## Current Behavior
`Collecting urllib3<1.23,>=1.21.1 (from requests[security]==2.18.4->-r requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 3.5MB/s
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 997, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 535, in get_distribution
    dist = get_provider(dist)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 415, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 808, in resolve
    if not req_extras.markers_pass(req):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 993, in markers_pass
    return not req.marker or any(extra_evals) or req.marker.evaluate()
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/markers.py", line 278, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/markers.py", line 203, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/markers.py", line 185, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
You are using pip version 8.1.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

## Your Environment
Ubuntu Server 16.04
Python 2.7.12
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by Bart274** [comment]
Hi,
Can you try upgrading your pip version first? You can upgrade it by running `pip install --upgrade pip`

**Comment by lamboid** [comment]
add `&& pip install --upgrade pip \` to Dockerfile and rebuilt.
Now cannot access MySql:

```
2019-01-30 10:40:38,548 [        MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "./runserver.py", line 438, in <module>
    main()
  File "./runserver.py", line 276, in main
    db = startup_db(app, args.clear_db)
  File "./runserver.py", line 162, in startup_db
    verify_database_schema(db)
  File "/usr/src/app/pogom/models.py", line 3888, in verify_database_schema
    if not Versions.table_exists():
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 4611, in table_exists
    return cls._meta.db_table in cls._meta.database.get_tables(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3932, in get_tables
    return [row for row, in self.execute_sql('SHOW TABLES')]
  File "/usr/local/lib/python2.7/site-packages/playhouse/shortcuts.py", line 207, in execute_sql
    cursor = self.get_cursor()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3431, in get_cursor
    return self.get_conn().cursor()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3424, in get_conn
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/site-packages/playhouse/pool.py", line 128, in _connect
    conn = super(PooledDatabase, self)._connect(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 690, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 939, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

```

**Comment by Bart274** [comment]
@lamboid sorry for the long delay, is this issue fixed yet? that issue is caused by your mysql server, not by RM++
